### ISSUE TITLE
Support directory as destination for source files with wildcard (*), in yaml config

### ISSUE THREAD

**Issue by damiencorpataux** [damiencorpataux/microdeploy#1]
Example yaml:
```yaml
packages:
  files:
    - ['lib/micropython/*.py', '/lib/.']
```

Notes:
- `/lib/.` is the explicit form, it can also be written `lib/`
  because starting `/` is implied and ending `/` is all that is needed
